
name: Mysql

on:
  workflow_dispatch:
    inputs:
      version_id:
        required: true
        default: think
        type: string
      product:
        required: true
        type: string
      name:
        required: true
        type: string
      version:
        required: true
        type: string


jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: [self-hosted, linux, x64, think]
    steps:
      - uses: actions/checkout@v3
      - uses: think-works/pull-image-action@main
        with:
          version_id: ${{ inputs.version_id }}
          product: ${{ inputs.product }}
          image: bitnami/mysql:${{ inputs.version }}
          name: ${{ inputs.name }}
          version: ${{ inputs.version }}
          arch: ${{ matrix.arch }}
