name: Success

on:
  workflow_dispatch:
    inputs:
      version_id:
        required: true
        default: think
        type: string
      product:
        required: true
        type: string
      name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:

  build:
    runs-on: [self-hosted, linux, x64, think]
    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir ${{ inputs.name }}
          cp -r ./* ${{ inputs.name }}
          tar zcvf ${{ inputs.name }}.tar.gz ${{ inputs.name }}
          echo "Success Build ${{ inputs.version_id }} ${{ inputs.product }} ${{ inputs.name }} ${{ inputs.version }}"

      - name: Upload To Oss
        uses: think-works/upload-to-oss@main
        with:
          version_id: ${{ inputs.version_id }}
          product: ${{ inputs.product }}
          name: ${{ inputs.name }}
          version: ${{ inputs.version }}
          arch: noarch
          file_name: ${{ inputs.name }}.tar.gz

      - name: Push Tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: ${{ github.sha }}
          tag: 'v${{ inputs.version }}'
          body: 'Release v${{ inputs.version }}'
